# --- 基础配置 ---
title: "*nix 的学习笔记"
url: "https://github.com/th1nk3r-ing" # 替换为你的 GitHub Pages 地址

# --- 作者信息 ---
author:
  name: "think3r"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/th1nk3r-ing"

# 深色主题
remote_theme: th1nk3r-ing/hacker@v0.2.0.2
# remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
